# Generated by Django 4.1.1 on 2022-10-02 19:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.CharField(max_length=200)),
                ("password", models.CharField(max_length=200)),
                ("account_creation", models.DateTimeField()),
                ("current_ip", models.GenericIPAddressField()),
            ],
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                (
                    "members",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="coms.user"
                    ),
                ),
            ],
        ),
    ]
