# Generated by Django 4.1.1 on 2022-10-02 19:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("coms", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="group",
            name="members",
        ),
        migrations.AlterField(
            model_name="user",
            name="uid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("time", models.DateTimeField()),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="coms.user"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="group",
            name="files",
            field=models.ManyToManyField(to="coms.file"),
        ),
        migrations.AddField(
            model_name="group",
            name="members",
            field=models.ManyToManyField(to="coms.user"),
        ),
    ]
