# Generated by Django 4.1.1 on 2022-10-03 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("coms", "0002_remove_group_members_alter_user_uid_file_group_files_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="File",
            new_name="FileModel",
        ),
        migrations.RenameModel(
            old_name="Group",
            new_name="GroupModel",
        ),
        migrations.RenameModel(
            old_name="User",
            new_name="UserModel",
        ),
    ]
