# Generated by Django 4.1.1 on 2022-10-03 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("coms", "0003_rename_file_filemodel_rename_group_groupmodel_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FileModel",
            new_name="File",
        ),
        migrations.RenameModel(
            old_name="GroupModel",
            new_name="Group",
        ),
        migrations.RenameModel(
            old_name="UserModel",
            new_name="User",
        ),
    ]
