# Generated by Django 4.1.1 on 2022-10-03 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coms", "0004_rename_filemodel_file_rename_groupmodel_group_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=30),
        ),
    ]
