# Generated by Django 4.1.1 on 2022-10-03 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("coms", "0005_alter_user_password"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="current_ip",
            new_name="last_known_ip",
        ),
    ]
