# Generated by Django 4.1.1 on 2022-10-03 14:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("coms", "0006_rename_current_ip_user_last_known_ip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="account_creation",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
