# Generated by Django 4.1.1 on 2022-10-03 14:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("coms", "0007_alter_user_account_creation"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="deactivated",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="last_seen",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="user",
            name="account_creation",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, editable=False
            ),
        ),
    ]
