# Generated by Django 4.1.1 on 2022-10-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coms", "0008_user_deactivated_user_last_seen_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="last_seen",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
