# Generated by Django 4.1.1 on 2022-10-04 15:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("coms", "0009_alter_user_last_seen"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="creation",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
