# Generated by Django 4.1.1 on 2022-10-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coms", "0011_rename_members_group_users_group_active_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="deactivated",
        ),
        migrations.AddField(
            model_name="user",
            name="active",
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
