# Generated by Django 4.1.1 on 2022-10-04 16:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coms", "0012_remove_user_deactivated_user_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="time_period",
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
        ),
    ]
