# Generated by Django 4.1.1 on 2022-10-04 16:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("coms", "0013_group_time_period"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="files",
            field=models.ManyToManyField(blank=True, to="coms.file"),
        ),
        migrations.AlterField(
            model_name="group",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="share_link",
            field=models.URLField(
                default="http://127.0.0.1:8000/api/group/<django.db.models.fields.UUIDField>/join/"
            ),
        ),
    ]
