# Generated by Django 4.1.1 on 2022-10-10 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coms", "0014_alter_group_files_alter_group_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(default="empty_name", max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.CharField(max_length=100),
        ),
    ]
