# Generated by Django 4.1.1 on 2022-10-10 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("coms", "0018_alter_group_share_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="group",
            name="share_link",
        ),
    ]
