# Generated by Django 4.1.3 on 2022-11-30 04:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="group",
            name="duration",
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
        ),
        migrations.AlterField(
            model_name="group",
            name="join_link",
            field=models.URLField(default=""),
        ),
    ]
