# Generated by Django 4.1.3 on 2022-11-30 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0002_session_active_alter_group_duration_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="created",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="group",
            name="end",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="group",
            name="start",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
